#!/bin/sh
if [ $# -eq 1 ]
then
  ADDRESS=""
  RECIP_FORENAME=""
  RECIP_SURNAME=""
  RECIP_GREETING="To Whom It May Concern"
  RECIP_SIGNOFF="Yours faithfully"
else
  ADDRESS="$2 \\\\ $3 \\\\ $4, $5 \\\\ $6"
  RECIP_FORENAME="$7"
  RECIP_SURNAME="$8"
  RECIP_GREETING="Dear $RECIP_FORENAME"
  RECIP_SIGNOFF="Yours sincerely"
fi

docker build -t pandoc .
docker run --rm --volume "`pwd`:/data" --user `id -u`:`id -g` pandoc --variable=address:"$ADDRESS" -M forename="$RECIP_FORENAME" -M surname="$RECIP_SURNAME" -M greeting="$RECIP_GREETING" -M signoff="$RECIP_SIGNOFF" "$1" --template=test.tex -o "out/$1.pdf"
